name: Python Tests and Linting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies and linters
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pylint

    - name: Run tests with unittest
      run: |
        python -m unittest discover -s tests -p "test_*.py"

    - name: Run Pylint
      run: |
        pylint py_stats_toolkit --fail-under=8.0
